import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Kanit } from '@next/font/google';
import NavBar from "@/components/NavBar";
import Header from "@/components/Header";

const kanit = Kanit({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit} antialiased h-screen`}
      >
        <Header/>
        {children}
        <NavBar/>
      </body>
    </html>
  );
}
