import type { Metadata } from "next";
import "./globals.css";
import { Kanit } from 'next/font/google';
import BottomBar from "@/components/layout/NavBar";
import Header from "@/components/layout/Header";

const kanit = Kanit({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className} antialiased h-screen flex flex-col`}
      >
        <Header />
        <main className="flex-grow py-8 px-6">
          {children}
        </main>
        <BottomBar IconSize={25} />
      </body>
    </html>
  );
}
